<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option): ?>
                <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                <dd>
                    <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>

        <?php //// Product Attachement code start ?>

        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $productAttachment = $objectManager->get('Prince\Productattach\Block\Attachment'); 
        $productId = $objectManager->get('Magento\Catalog\Model\Product')->getIdBySku($block->getSku($_item));

        ?>

        <div class="attachments">
            <?php if($productAttachment->isEnable()): ?>                                
                <?php $attachments = $productAttachment->getAttachment($productId); ?>  
                <?php if(count($attachments)){ ?>
                    <div class="label"><b>Product Artwork File</b></div>
                    <?php $isSize = $productAttachment->getConfig('productattach/general/attachmentsize'); ?>
                    <?php foreach ($attachments as $attachment) : ?>
                        <?php if ($attachment->getActive()) : ?>
                            <div class="product-attachment" style="margin-bottom: 10px;">
                                <?php if ($attachment->getFile()) : ?>
                                    <a href="<?php /* @noEscape */ echo $productAttachment->getAttachmentUrl($attachment->getFile()); ?>" target="_blank">
                                        <div class="attachment-icon" style="float: left; padding-right: 10px;">
                                            <img src="<?php /* @noEscape */ echo $productAttachment->getFileIcon($attachment->getFileExt()) ?>" style="width: 20px"/>
                                        </div>
                                        <?php /* @noEscape */ echo $attachment->getName(); ?>
                                    </a>
                                    <?php if ($isSize) : ?>
                                        <?php $size = '(Size: '.$productAttachment->getFileSize($attachment->getFile()).')' ?>
                                        <?php /* @noEscape */ echo __($size); ?>
                                    <?php endif; ?>
                                <?php elseif ($attachment->getUrl()) : ?>
                                    <a href="<?php /* @noEscape */ echo $attachment->getUrl(); ?>" target="_blank" >
                                        <div class="attachment-icon" style="float: left; padding-right: 10px;">
                                            <img src="<?php /* @noEscape */ echo $productAttachment->getLinkIcon(); ?>" />
                                        </div>
                                        <?php /* @noEscape */ echo $attachment->getName(); ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php  } ?>
            <?php endif; ?>
        </div>

        <?php /// Product attachement code end ?>

    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="3" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                    <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
