<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

      <div class="col-lg-6 mail">
        
        <h2>Mail</h2>
        <div class="subheading">Send anything that needs to be posted to us by mail using the address below.</div>
        <div class="content">
        	<div class="business-address"></div>
        	<a class="btn btn-primary" href="#" role="button">View our Location</a>
        </div>

      </div><!-- /.col-lg-4 -->
      <div class="col-lg-6 email">
        
        <h2>Email</h2>
        <div class="subheading">Email our product experts on the email addresses provided below.</div>
        <div class="content">
        	<a class="btn btn-primary" href="#" role="button">Use Contact Form</a>
        </div>
        
      </div><!-- /.col-lg-4 -->
      
      <div class="col-lg-6 phone">
        
        <h2>Phone</h2>
        <div class="subheading">Fancy speaking to a human being? Here's a list of useful numbers.</div>
        <div class="content">
        	<div class="contact-info sales">Sales Team - <span>0116 2666 227</span></div>
        	<div class="contact-info switchboard">Switchboard - <span>0116 2666 227</span></div>
        	<a class="btn btn-primary" href="tel:01162666227" role="button">Call Now</a>
        </div>

      </div><!-- /.col-lg-4 --><div class="col-lg-6 online-chat">
        
        <h2>Online Chat</h2>
        <div class="subheading">Chat to our Product experts using our online chat. Simply click the button below to start a chat.</div>
        <div class="content">
        	<a class="btn btn-primary" href="javascript:void(Tawk_API.toggle())" role="button">Click to Chat</a>
        </div>
        
      </div><!-- /.col-lg-4 -->