<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct();
$_callhelper = $this->helper('Magecomp\Hideprice\Helper\Data'); 
$_calldata = $_callhelper->getHideprice($_product->getId());?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset" style="text-align: center;">
            <?php if ($block->shouldRenderQuantity()): ?>
                <?php if(!sizeof($_calldata)):?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                   />
                        </div>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php if(sizeof($_calldata)): ?>
    				<a href="<?php echo $this->getUrl($_callhelper->getCmspagelink()); ?>"><button type="button" title="<?php echo $_calldata['button_text']; ?>" class="action tocart primary" style="width: 20%;"><span><?php /* @escapeNotVerified */ echo $_calldata['button_text'] ?></span></button></a>
                    <p class="productpage-login-note">After login you can download artwork template, view price and options.</p>
    		<?php else: ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            <?php endif;?>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>